name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.x for linting
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
      env:
        CI: true
    - name: Execute TypeScript linting
      run: npm run lint
      env:
        CI: true
